body:
- type: input
  attributes:
    label: MagickCache version
    placeholder: 1.X.X-X
  validations:
    required: true
- type: input
  attributes:
    label: Operating system, version and so on
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
  validations:
    required: true
